ArmstrongNum.java
FibonacciSeries.java

added two programs that are interview based questions

Added armstrong and fibonacci program

---

KadanesAlgo.java

I had added kadane's algorithm in java . Please merge it.

Added Kadane's Algorithm

---

PowerSet.cpp

Power Set is set of all subsets, It is a must to do Interview Question.
Kindly Merge it in your repo.
@vishal8113

Added code for obtaining Power Set in c++

---

MatrixRotation.cpp

This is also a very popular interview question.
We should tell the naive approach first to the interviewer, then he will surely asks for optimization, then tell him the Efficient approach and he will be happy.

Added Anticlockwise Matrix Rotation by 90 degree program in C++

---

duplicates in an array.cpp

added a CPP code to find duplicate elements in an array

 code to find duplicate elements in an array, hactoberfest2022

---

Rat in a Maze.cpp

contributed the code of rat in a maze,pls check it and merge.

Create Rat in a Maze.cpp

---

ActivitySelection.cpp

Activity selection in a greedy approach, and also asked in many interviews.
(like Morgan Stanley, flipkart,facebook)

Added ActivitySelection.cpp which is a must do question.

---

Longest Common Prefix.cpp
find-all-pairs-whose-sum-is-x.cpp
parenthesis_checker.cpp

1. Longest Common Prefix
2. find-all-pairs-whose-sum-is-x
3. Parenthesis Checker

added 3 new questions:

---

CPP/Median_of_running_stream_of_integers.cpp
CPP/Valid_paranthesis.cpp

Here I have added codes that have been asked to me during interview at MicroSoft.

added cpp codes- asked in MS

---

CPP/Generate_Paranthesis_BackTracking.cpp

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

 Added Generating Paranthesis(BackTracking) solution (asked in MS Round1)

---

CPP/stackusinglinkedlist.cpp

The given Cpp program implements stack using linked lists. It is implemented using class. Different methods such as push,pop and display are included.

Cpp program on stack using linked lists.

---

Fibonacci series.c

Added code for Fibonacci series

---

CPP/intersection_of_two_linked_list.cpp

I have added optimal code for finding intersection of two linked list in C++ language.

Added Intersection of Two Linked List

---

Tower_of_hanoi.cpp

tower_of_hanoi

---

Python/BinarySearch.py

This PR is related to [issue#1](https://github.com/vishal8113/Hacktoberfest-Interview-Questions/issues/1)

Added Binary search question in Python language

---

CPP/Binary_Search.cpp

Please merge this pull request

Added Binary Search Program in C++

---

CPP/Linear_Search.cpp

Please merge my pull request.......

Added Linear Search program in C++

---

star pattern in c++.cpp

Added star pattern in cpp.

---

CPP/Rotate_Matrix.cpp

I have added Rotate Matrix question in CPP folder
Problem Statement: Given a square matrix. Your task is to rotate the matrix 90* in clockwise direction

Added Rotate Matrix in CPP

---

CPP/Treesort.cpp

 Treesort ,Hacktoberfest

---

CPP/#include<stdio.h> #include<conio.h> int main() {     int mat[3][3], i, j, matTrans[3][3];     printf("Enter 3*3 Matrix Elements: ");     for(i=0; i<3; i++)     {         for(j=0; j<3; j++)             scanf("%d", &mat[i][j]);     }/Transpose_Matrix.c

Transpose of a Matrix

---

Java/HeapSort.java

Kindly merge this pull request asap!! Thanks :))

Heap Sort in Java is added!!

---

CPP/InsertionSort.cpp

Kindly merge this pull request asap!!

Insertion Sort Program in C++ is added !

---

SieveOfEratosthenes.cpp

Added code for Sieve Of Eratosthenes

---

CPP/leapyear.cpp
CPP/opamgnum.cpp

i just add a cpp snippet , it is actually the computational operastions of two numbers , through that user can get any computational operation of his choice of the two numbers which are provided by user too.

computationaloperationsoftwonumbers.cpp

---

CPP/linear.cpp

i just uploaded the cpp code snippet , user can enter the numbers of their choice and by giving a number code can able to find the certain number is in given list or not, and the sequence number if found.

linearsearch.cpp

---

Bubble_Sort

Bubble Sort in Java

---

Merge_k_Sorted_Lists.cpp

Added Merge_k_Sorted_Lists solution

---

CPP/FindPermutationSequence.cpp

We have to find the Permutation sequence for given permutation. Explained solution along with relevant comments are added.

Code to find Permutation sequence of a give permutation.

---

Kth Smallest_Element_in_a_BST.cpp

Solution 01
Using Vector.
Here we’ll do inorder traversal, which is (left subtree → root → right subtree). We’ll store the values from the left side in our vector, which will be in increasing order. Finally, we’ll return (k-1) element from our vector, as it’s in increasing order so it will be kth smallest element. Time complexity: O(n), as we’re traversing the whole tree once.
Solution 02
Using Recursion.
if we do inorder traversal then in kth iteration we’ll get our ans. return the ans.
Time complexity: O(n).

Added solution for Kth Smallest_Element_in_a_BST

---

Construct_Binary_Tree_from_Preorder_and_Inorder_Traversal.cpp

Here we have to Construct Binary Tree from Preorder and Inorder Traversal. You need to understand preorder and postorder traversal first, and then go ahead.
The basic idea is:
preorder[0] is the root node of the tree
preorder[x] is a root node of a sub tree
In in-order traversal
When inorder[index] is an item in the in-order traversal inorder[0]-inorder[index-1] are on the left branch inorder[index+1]-inorder[size()-1] are on the right branch if there is nothing on the left, that means the left child of the node is NULL if there is nothing on the right, that means the right child of the node is NULL
Algorithm:
Start from rootIdx 0
Find preorder[rootIdx] from inorder, let's call the index pivot Create a new node with inorder[pivot]
Create its left child recursively
Create its right child …

Added solution for Construct Binary Tree

---

CPP/Merge_Intervals.cpp

We have to merge the overlapping intervals . Explained solution along with relevant comments are added.

 Solution to merge intervals to overcome Overlapping intervals.

---

CPP/MatrixToSpiralMatrix.cpp
CPP/Wildcard_Pattern_Matching.cpp
CPP/minimum partition.cpp

If you find my codes interesting please accept my pull request

added few cpp codes

---

CPP/matrixChainMultiplication.cpp

added problem and solution for matrixChainMultiplication in cpp language.

added matrixChainMultiplication Code

---

bubble sort .cpp

Here is my code of bubble .please check it and kindly merged it.

Create bubble sort .cpp

---

generate_parenthesis.java

Hi Vishal,
I have added solution for leetcode problem (22. Generate Parentheses),in file named as generate_parenthesis.java.
Please do have a look at it.
Thank you,

added generate_parenthesis.java file

---

deleteMiddleOfLinkedList.java
deleteNodeInLinkedList.java

Hi Vishal,
I have added code for leetcode problem (237. Delete Node in a Linked List).Please have a look.
Thank you

added code for deleteNodeInLinkedList

---

Java/SortStack.java

I have Created a Java_program_to_sort_an_array_using_stack.

Java_program_to_sort_an_array_using_stack

---

Java/Test.java

Here I have Created a Program to cyclically rotate an array by one.

java_code_to_cyclically_rotate_an_array_by_one

---

CPP/knapsack-problem.cpp

consider my contribution, I have added the code of knap sack problem in cpp please merge it under hactoberfest2022

added the code of knapsack problem

---

Java/ArrRotate.java
Java/BSTSort.java
Java/CompStr.java
Java/SphenicNo.java
Java/SteinsAlgo.java
Java/angramProg.java
Java/rrRotate.java

Here I have Created a Program of Sphenic numbers in java.

Sphenic number in java

---

Java/ArrRotate.java
Java/rrRotate.java

Here I have Created a Java program to block swap algorithm for array rotation.

Java program to block swap algorithm for array rotation

---

CPP/snake.cpp

As part of hacktoberfest contribution adding cpp game

Snake Game

---

CPP/Consecutive.cpp
CPP/Test score.cpp
codechef_solutions/minimum_coins.cpp

Please merge this commit with the upstream.

Codechef solution for Test Score

---

CPP/book shop.cpp

book shop in c++
